// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnedById")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnedById");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            OwnedById = 1,
                            Value = "0xAC233FAB9B9F"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            OwnedById = 2,
                            Value = "0x3530A832"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            OwnedById = 2,
                            Value = "0xE5B2B932"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            OwnedById = 3,
                            Value = "0x5541A832"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            OwnedById = 3,
                            Value = "0xB5E2A732"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            OwnedById = 3,
                            Value = "0x15B4B932"
                        });
                });

            modelBuilder.Entity("backend.Models.Entities.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Charger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreatedAt = new DateTime(2023, 12, 30, 15, 41, 45, 617, DateTimeKind.Utc).AddTicks(4993),
                            CreatedById = 1,
                            LastSyncAt = new DateTime(2023, 12, 30, 16, 41, 45, 617, DateTimeKind.Utc).AddTicks(4996),
                            Latitude = 46.309735000000003,
                            Longitude = 16.348593000000001,
                            Name = "Charger Dorm"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreatedAt = new DateTime(2023, 12, 30, 15, 41, 45, 617, DateTimeKind.Utc).AddTicks(5003),
                            CreatedById = 1,
                            LastSyncAt = new DateTime(2023, 12, 30, 17, 41, 45, 617, DateTimeKind.Utc).AddTicks(5004),
                            Latitude = 46.287309,
                            Longitude = 16.321732999999998,
                            Name = "Charger Mobilisis"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            CreatedAt = new DateTime(2023, 12, 30, 15, 41, 45, 617, DateTimeKind.Utc).AddTicks(5006),
                            CreatedById = 1,
                            LastSyncAt = new DateTime(2023, 12, 30, 18, 41, 45, 617, DateTimeKind.Utc).AddTicks(5006),
                            Latitude = 46.307789999999997,
                            Longitude = 16.338061,
                            Name = "Charger FOI"
                        });
                });

            modelBuilder.Entity("backend.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("ChargerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VolumeKwh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ChargerId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            ChargerId = 1,
                            EndedAt = new DateTime(2023, 12, 30, 16, 11, 45, 617, DateTimeKind.Utc).AddTicks(5035),
                            StartedAt = new DateTime(2023, 12, 30, 13, 41, 45, 617, DateTimeKind.Utc).AddTicks(5034),
                            VolumeKwh = 9.8000000000000007
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            ChargerId = 1,
                            EndedAt = new DateTime(2023, 12, 30, 16, 21, 45, 617, DateTimeKind.Utc).AddTicks(5037),
                            StartedAt = new DateTime(2023, 12, 30, 14, 41, 45, 617, DateTimeKind.Utc).AddTicks(5036),
                            VolumeKwh = 7.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CardId = 2,
                            ChargerId = 2,
                            EndedAt = new DateTime(2023, 12, 30, 16, 16, 45, 617, DateTimeKind.Utc).AddTicks(5158),
                            StartedAt = new DateTime(2023, 12, 30, 13, 41, 45, 617, DateTimeKind.Utc).AddTicks(5158),
                            VolumeKwh = 5.0999999999999996
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            ChargerId = 2,
                            EndedAt = new DateTime(2023, 12, 30, 16, 26, 45, 617, DateTimeKind.Utc).AddTicks(5160),
                            StartedAt = new DateTime(2023, 12, 30, 14, 41, 45, 617, DateTimeKind.Utc).AddTicks(5160),
                            VolumeKwh = 14.6
                        },
                        new
                        {
                            Id = 5,
                            CardId = 4,
                            ChargerId = 3,
                            EndedAt = new DateTime(2023, 12, 30, 16, 36, 45, 617, DateTimeKind.Utc).AddTicks(5162),
                            StartedAt = new DateTime(2023, 12, 30, 12, 41, 45, 617, DateTimeKind.Utc).AddTicks(5162),
                            VolumeKwh = 11.300000000000001
                        },
                        new
                        {
                            Id = 6,
                            CardId = 1,
                            ChargerId = 1,
                            EndedAt = new DateTime(2023, 12, 30, 16, 6, 45, 617, DateTimeKind.Utc).AddTicks(5164),
                            StartedAt = new DateTime(2023, 12, 30, 12, 41, 45, 617, DateTimeKind.Utc).AddTicks(5163),
                            VolumeKwh = 7.5
                        },
                        new
                        {
                            Id = 7,
                            CardId = 1,
                            ChargerId = 2,
                            EndedAt = new DateTime(2023, 12, 30, 16, 21, 45, 617, DateTimeKind.Utc).AddTicks(5166),
                            StartedAt = new DateTime(2023, 12, 30, 11, 41, 45, 617, DateTimeKind.Utc).AddTicks(5165),
                            VolumeKwh = 8.9000000000000004
                        },
                        new
                        {
                            Id = 8,
                            CardId = 3,
                            ChargerId = 3,
                            EndedAt = new DateTime(2023, 12, 30, 16, 31, 45, 617, DateTimeKind.Utc).AddTicks(5167),
                            StartedAt = new DateTime(2023, 12, 30, 13, 41, 45, 617, DateTimeKind.Utc).AddTicks(5167),
                            VolumeKwh = 10.199999999999999
                        });
                });

            modelBuilder.Entity("backend.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiresAt = new DateTime(2023, 12, 31, 15, 41, 45, 434, DateTimeKind.Utc).AddTicks(9673),
                            Token = "0x1A2B3C4F5D6EAES3DF4FFDE4"
                        });
                });

            modelBuilder.Entity("backend.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("backend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<int?>("RefreshTokenId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2023, 12, 30, 15, 41, 45, 434, DateTimeKind.Utc).AddTicks(9692),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "AQAAAAIAAYagAAAAEJjE2/NpiUFySqgSdGs/W+6jU7LhsMZOS/WMdB2fDGVofzwb+6a3Hlt6YvjVCpTQIA==",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2023, 12, 30, 16, 41, 45, 496, DateTimeKind.Utc).AddTicks(1972),
                            Email = "user@gmail.com",
                            FirstName = "User",
                            LastName = "User",
                            Password = "AQAAAAIAAYagAAAAEJGPR4geK2d5Mu99mexALH3+8ua8Q5D9OJn/mmh/7f6DUyKfcUw/wdVMo2k9aifa/w==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2023, 12, 30, 17, 41, 45, 556, DateTimeKind.Utc).AddTicks(6480),
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "AQAAAAIAAYagAAAAEOrQZh52ppRplgha3Nc91Z33gE6YxO71ZeF1X98t2Quu40BzsMNncssOPAjDscD1IA==",
                            RefreshTokenId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("backend.Models.Entities.Card", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "OwnedBy")
                        .WithMany()
                        .HasForeignKey("OwnedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnedBy");
                });

            modelBuilder.Entity("backend.Models.Entities.Charger", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("backend.Models.Entities.Event", b =>
                {
                    b.HasOne("backend.Models.Entities.Card", "Card")
                        .WithMany("Events")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Entities.Charger", "Charger")
                        .WithMany("Events")
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("backend.Models.Entities.User", b =>
                {
                    b.HasOne("backend.Models.Entities.RefreshToken", "RefreshToken")
                        .WithMany()
                        .HasForeignKey("RefreshTokenId");

                    b.HasOne("backend.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefreshToken");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Entities.Card", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("backend.Models.Entities.Charger", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
